#!/bin/bash

source <(curl -s https://raw.githubusercontent.com/silvagpmiguel/license-prepender/main/src/license_env)
source <(curl -s https://raw.githubusercontent.com/silvagpmiguel/license-prepender/main/src/functions) --source-only

while :; do
    case $1 in
        -h|--help)
            usage
        ;;
        -l|--license)
            [[ "$2" != "" ]] && LICENSE_NAME=$( echo "$2" | tr '[:upper:]' '[:lower:]' );shift || usage "Wrong usage."
        ;;
        -a|--author)
            [[ "$2" != "" ]] && AUTHOR="$2";shift || usage "Wrong usage."
        ;;
        -y|--year)
            [[ "$2" != "" ]] && DATE="$2";shift || usage "Wrong usage."
        ;;
        -p|--path)
            [[ "$2" != "" ]] && REPO_PATH="$2";shift || usage "Wrong usage."
        ;;
        -d|--description)
            [[ "$2" != "" ]] && DESCRIPTION="$2";shift || usage "Wrong usage."
        ;;
        -dr|--dry-run)
            DRY_RUN=true
        ;;
        "")
            [[ ${LICENSE_NAME} == "" ]] && usage "Wrong usage." || break
        ;;
        *)
            usage "Wrong usage."
        ;;
    esac
    shift
done


if ${DRY_RUN}; then
    echo "This is a dry run, changes will not be made"
fi

if [[ "${LICENSES[$LICENSE_NAME]}" != "" ]]; then
    echo "Add license file in ${REPO_PATH}LICENSE"
    if ! ${DRY_RUN}; then
        addLicense
    fi
fi

if [[ "${BOILERPLATES[$LICENSE_NAME]}" != "" ]]; then
    HAS_BOILERPLATE=true
    getLicenseBoilerplate
fi

for key in "${!SUPPORTED[@]}"; do
    FOUND_PATHS=$(find "$REPO_PATH" -type f -name "*$key")
    case "${SUPPORTED[$key]}" in
        "//")
            prepend "$key" "${FOUND_PATHS[@]}" "" "" "// " ${HAS_BOILERPLATE}
        ;;
        "/*")
            prepend "$key" "${FOUND_PATHS[@]}" "/*\n" " */" " * " ${HAS_BOILERPLATE}
        ;;  
        "<!--")
            prepend "$key" "${FOUND_PATHS[@]}" "<!--\n" "-->" "~ " ${HAS_BOILERPLATE}
        ;;
    esac
done