#!/usr/bin/env bash

function usage() {
printf "$1"
cat << EOF
Usage: license-prepender [flags]
-h      --help                       Show help
-l      --license       <STRING>     Choose a license
-a      --author        <STRING>     Set Author name
-y      --year          <STRING>     Set Year
-p      --path          <STRING>     Set Repository path (default: './')
-d      --description   <STRING>     Set Description
-dr     --dry-run                    Show files affected by boilerplate prepend and don't execute
EOF
exit
}

function getLicenseBoilerplate() {
    local boilerplate=$(curl -s "${BOILERPLATES[$LICENSE_NAME]}")
    if [[ "${DESCRIPTION}" != "" ]]; then
        BOILERPLATE_CONTENT=$(echo -e "${boilerplate}" | sed -e "s/\[DESCRIPTION\]/$DESCRIPTION/" \
            -e "s/\[YEAR\]/${DATE}/" \
            -e "s/\[NAME\]/${AUTHOR}/")
    else
        BOILERPLATE_CONTENT=$(echo -e "${boilerplate}" | sed -e "s/\[YEAR\]/${DATE}/" \
            -e "s/\[NAME\]/${AUTHOR}/")
    fi
}

function addLicense() {
    LICENSE_CONTENT=$(curl -s "${LICENSES[$LICENSE_NAME]}")
    if [[ "$LICENSE_NAME" == "mit" ]]; then
        echo -e "$LICENSE_CONTENT" | sed -e "s/\[YEAR\]/${DATE}/" \
            -e "s/\[NAME\]/${AUTHOR}/" > "${REPO_PATH}/LICENSE"
    else
        echo -e "${LICENSE_CONTENT}" > "${REPO_PATH}/LICENSE"
    fi
}

function isBoilerplatePresent() {
    [[ $(grep -Fo "$1" "$2" | wc -l) != "0" ]]
}

function getCommentedBoilerplate() {
    local license="$2"
    while read line; do
        license="${license}$4${line}\n"
    done <<< ${BOILERPLATE_CONTENT[@]}
    license="${license}$3"
    echo -e "${license}"
}

function prepend() {
    if $6; then
        local paths="$2"
        IFS=$'\n'; for p in $paths; do
            IFS=' '; for subp in $p; do
                if ! isBoilerplatePresent "${BOILERPLATE_CONTENT}" "${subp}"; then
                    echo "Boilerplate prepended in ${subp}"
                    if ! ${DRY_RUN}; then
                        local commented_boilerplate=$(getCommentedBoilerplate "${LICENSE_NAME}" "$3" "$4" "$5")
                        echo -e "${commented_boilerplate}\n\n\n$(cat ${subp})" > "${subp}"
                    fi
                fi
            done
        done
    fi
}